// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "contacts_ui.h"

ContactsUI app;

void ContactsUI::cb_cnt_list_i(Fl_Browser*, void*) {
  // list callback;
	int selected = cnt_list->value();
}
void ContactsUI::cb_cnt_list(Fl_Browser* o, void* v) {
	((ContactsUI*)(o->parent()->user_data()))->cb_cnt_list_i(o,v);
}

void ContactsUI::cb_Call_i(Fl_Menu_*, void*) {
  //call current contact;
	refresh_list("");
}
void ContactsUI::cb_Call(Fl_Menu_* o, void* v) {
  ((ContactsUI*)(o->parent()->user_data()))->cb_Call_i(o,v);
}

void ContactsUI::cb_Open_i(Fl_Menu_*, void*) {
  // open current contact to view details;
}
void ContactsUI::cb_Open(Fl_Menu_* o, void* v) {
  ((ContactsUI*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void ContactsUI::cb_Edit_i(Fl_Menu_*, void*) {
  // edit contact;
}
void ContactsUI::cb_Edit(Fl_Menu_* o, void* v) {
  ((ContactsUI*)(o->parent()->user_data()))->cb_Edit_i(o,v);
}

Fl_Menu_Item ContactsUI::menu_LeftSoft[] = {
 {"Call", 0,  (Fl_Callback*)ContactsUI::cb_Call, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Open", 0,  (Fl_Callback*)ContactsUI::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Edit", 0,  (Fl_Callback*)ContactsUI::cb_Edit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void ContactsUI::cb_RightSoft_i(Fl_Menu_Button*, void*) {
  // Close program;
	exit(1);
}
void ContactsUI::cb_RightSoft(Fl_Menu_Button* o, void* v) {
  ((ContactsUI*)(o->parent()))->cb_RightSoft_i(o,v);
}


ContactsUI::ContactsUI()
  : Fl_App("Contacts")
{
	user_data(this);

{ Fl_Select_Browser* o = cnt_list = new Fl_Select_Browser(0, 0, 176, 180);
  o->callback((Fl_Callback*)cb_cnt_list);
  o->user_data(this);
  o->align(FL_ALIGN_CENTER);
}
{ Fl_Group* o = grp_view = new Fl_Group(0, 0, 176, 180, "Call");
  o->hide();
  o->user_data(this);
  o->end();
}
{ Fl_Group* o = grp_edit = new Fl_Group(0, 0, 176, 180);
  o->hide();
  o->user_data(this);
  o->end();
}

  AppArea->add(cnt_list);

  LeftSoftMenu->menu(menu_LeftSoft);
  RightSoftMenu->callback((Fl_Callback*)cb_RightSoft);

  pim_init();

}

void ContactsUI::refresh_list(char *filter)
{
  // fill contact list with data
// use filter
	char **azResult;
	int RowNum;

	cnt_list->clear();

	pim_get_contacts(filter, &azResult, &RowNum);

	for(int i = 1; i <= RowNum; i++)
		cnt_list->add(azResult[i*2+1]/*, azResult[i*2]*/);

	pim_free_result(azResult);
}

int main(int argc, char **argv)
{
	app.show(argc,argv);
	app.refresh_list("");

	return Fl::run();
}
