// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef contacts_ui_h
#define contacts_ui_h
#include <FL/Fl.H>
#include <flgui/Fl_App.h>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Select_Browser.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Menu_Button.H>

#include <flphone/libpim.h>

class ContactsUI : public Fl_App {
public:
  ContactsUI();
  Fl_Select_Browser *cnt_list;
private:
  void cb_cnt_list_i(Fl_Browser*, void*);
  static void cb_cnt_list(Fl_Browser*, void*);
public:
  Fl_Group *grp_view;
  Fl_Group *grp_edit;
  static Fl_Menu_Item menu_LeftSoft[];
private:
  void cb_Call_i(Fl_Menu_*, void*);
  static void cb_Call(Fl_Menu_*, void*);
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Edit_i(Fl_Menu_*, void*);
  static void cb_Edit(Fl_Menu_*, void*);
public:
private:
  void cb_RightSoft_i(Fl_Menu_Button*, void*);
  static void cb_RightSoft(Fl_Menu_Button*, void*);
public:
  void refresh_list(char *filter);
};
#endif
