// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef dialer_h
#define dialer_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Menu_Button.H>

#include <libgsmd/libgsmd.h>

class DialerProgramUI: public Fl_Window
{
  private:
    int handle_key(int event, int key);
    Fl_Output *label1;
    Fl_Output *label2;    
    Fl_Menu_Button *menu_left;
//    static Fl_Menu_Item menu_menu_left[];
    
    char* num_td ;    
    static struct lgsm_handle *lgsmh;
    
  public:
    int handle(int e);  
    DialerProgramUI(int width, int height);
    
    static Fl_Menu_Item menu_menu_left[];    
    
    void cb_Select_i(Fl_Menu_*, void*);
    static void cb_Select(Fl_Menu_*, void*);    
};

#endif
