// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Menu_Button.H>

class TestProgramUI {
public:
  TestProgramUI();
  Fl_Window *win;
  Fl_Output *label1;
  Fl_Menu_Button *menu_left;
  static Fl_Menu_Item menu_menu_left[];
private:
  void cb_Select_i(Fl_Menu_*, void*);
  static void cb_Select(Fl_Menu_*, void*);
  void cb_Select1_i(Fl_Menu_*, void*);
  static void cb_Select1(Fl_Menu_*, void*);
  void cb_Select3_i(Fl_Menu_*, void*);
  static void cb_Select3(Fl_Menu_*, void*);
public:
  Fl_Menu_Button *menu_right;
  static Fl_Menu_Item menu_menu_right[];
private:
  void cb_Close_i(Fl_Menu_*, void*);
  static void cb_Close(Fl_Menu_*, void*);
public:
  void show(int argc, char **argv);
};
#endif
