// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef phone_h
#define phone_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win_phone;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *maintab;
#include <FL/Fl_Group.H>
extern Fl_Group *grp_dial;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_dial;
extern Fl_Button *btn_sms;
#include <FL/Fl_Input.H>
extern Fl_Input *dial_num;
extern Fl_Group *grp_call;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *hint;
extern Fl_Text_Display *contact_name;
extern Fl_Text_Display *phone_number;
extern Fl_Button *btn_end_call;
#include <FL/Fl_Menu_Button.H>
extern Fl_Menu_Button *LeftSoft;
extern Fl_Menu_Button *RightSoft;
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_LeftSoft[];

#endif
