// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef phone_h
#define phone_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Menu_Button.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *win_phone;
  Fl_Tabs *maintab;
  Fl_Group *grp_dial;
  Fl_Input *dial_num;

private:
  void cb_dial_num_i(Fl_Input*, void*);
  static void cb_dial_num(Fl_Input*, void*);
public:
  Fl_Button *btn_dial;
private:
  void cb_btn_dial_i(Fl_Button*, void*);
  static void cb_btn_dial(Fl_Button*, void*);
public:
  Fl_Group *grp_call;
  Fl_Text_Display *hint;
  Fl_Text_Display *contact_name;
  Fl_Text_Display *phone_number;
  Fl_Button *btn_answer;
private:
  void cb_btn_answer_i(Fl_Button*, void*);
  static void cb_btn_answer(Fl_Button*, void*);
public:
  Fl_Button *btn_end_call;
private:
  void cb_btn_end_call_i(Fl_Button*, void*);
  static void cb_btn_end_call(Fl_Button*, void*);
public:
  Fl_Group *grp_history;
  Fl_Browser *history;
private:
  void cb_history_i(Fl_Browser*, void*);
  static void cb_history(Fl_Browser*, void*);
public:
  Fl_Menu_Button *LeftSoft;
  static Fl_Menu_Item menu_LeftSoft[];
private:
  void cb_Dial_i(Fl_Menu_*, void*);
  static void cb_Dial(Fl_Menu_*, void*);
  void cb_Copy_i(Fl_Menu_*, void*);
  static void cb_Copy(Fl_Menu_*, void*);
public:
  Fl_Menu_Button *RightSoft;
private:
  void cb_RightSoft_i(Fl_Menu_Button*, void*);
  static void cb_RightSoft(Fl_Menu_Button*, void*);
};
#endif
