// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "phone.h"
// #include "phone_int.h"

Fl_Double_Window *win_phone=(Fl_Double_Window *)0;

Fl_Tabs *maintab=(Fl_Tabs *)0;

Fl_Group *grp_dial=(Fl_Group *)0;

Fl_Button *btn_dial=(Fl_Button *)0;

static void cb_btn_dial(Fl_Button*, void*) {
  // start a phone call
// animate when ringing
// activate Call tab when connected;
}

Fl_Button *btn_sms=(Fl_Button *)0;

Fl_Input *dial_num=(Fl_Input *)0;

static void cb_dial_num(Fl_Input*, void*) {
  // check value to fit to phone number
// 0..9 , + , p , w;
}

Fl_Group *grp_call=(Fl_Group *)0;

Fl_Text_Display *hint=(Fl_Text_Display *)0;

Fl_Text_Display *contact_name=(Fl_Text_Display *)0;

Fl_Text_Display *phone_number=(Fl_Text_Display *)0;

Fl_Button *btn_end_call=(Fl_Button *)0;

static void cb_btn_end_call(Fl_Button*, void*) {
  // end call;
}

Fl_Menu_Button *LeftSoft=(Fl_Menu_Button *)0;

static void cb_Call(Fl_Menu_*, void*) {
  // call option;
}

static void cb_Copy(Fl_Menu_*, void*) {
  // copy option;
}

Fl_Menu_Item menu_LeftSoft[] = {
 {"Call", 0,  (Fl_Callback*)cb_Call, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Copy", 0,  (Fl_Callback*)cb_Copy, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Button *RightSoft=(Fl_Menu_Button *)0;

static void cb_RightSoft(Fl_Menu_Button*, void*) {
  // Close program;
}

Fl_Double_Window* make_window() {
  { win_phone = new Fl_Double_Window(176, 200, "Phone");
    { maintab = new Fl_Tabs(0, 0, 176, 180);
      { grp_dial = new Fl_Group(0, 20, 176, 160, "Dial");
        { btn_dial = new Fl_Button(10, 90, 147, 25, "Call  @->");
          btn_dial->callback((Fl_Callback*)cb_btn_dial);
        } // Fl_Button* btn_dial
        { btn_sms = new Fl_Button(11, 131, 57, 25, "SMS");
        } // Fl_Button* btn_sms
        { dial_num = new Fl_Input(10, 34, 142, 24);
          dial_num->box(FL_FLAT_BOX);
          dial_num->callback((Fl_Callback*)cb_dial_num);
          dial_num->when(FL_WHEN_CHANGED);
        } // Fl_Input* dial_num
        grp_dial->end();
      } // Fl_Group* grp_dial
      { grp_call = new Fl_Group(0, 20, 176, 160, "Call");
        grp_call->hide();
        { hint = new Fl_Text_Display(10, 30, 147, 25);
          hint->deactivate();
        } // Fl_Text_Display* hint
        { contact_name = new Fl_Text_Display(10, 54, 147, 25);
          contact_name->labeltype(FL_NO_LABEL);
          contact_name->deactivate();
        } // Fl_Text_Display* contact_name
        { phone_number = new Fl_Text_Display(10, 78, 147, 25);
          phone_number->deactivate();
        } // Fl_Text_Display* phone_number
        { btn_end_call = new Fl_Button(10, 136, 147, 25, "End call  @square");
          btn_end_call->callback((Fl_Callback*)cb_btn_end_call);
        } // Fl_Button* btn_end_call
        grp_call->end();
      } // Fl_Group* grp_call
      maintab->end();
    } // Fl_Tabs* maintab
    { LeftSoft = new Fl_Menu_Button(0, 180, 88, 20, "Options");
      LeftSoft->menu(menu_LeftSoft);
    } // Fl_Menu_Button* LeftSoft
    { RightSoft = new Fl_Menu_Button(88, 180, 88, 20, "Close");
      RightSoft->callback((Fl_Callback*)cb_RightSoft);
      RightSoft->when(FL_WHEN_ENTER_KEY_ALWAYS);
    } // Fl_Menu_Button* RightSoft
    win_phone->end();
  } // Fl_Double_Window* win_phone
  return win_phone;
}

int main(int argc, char **argv)
{
	int fd_ipc;
	int fd_lgsm;

	fd_ipc = init_ipc();
	fd_lgsm = init_lgsm();

	// add fd of IPC messages
	Fl::add_fd(fd_ipc, handle_ipc);
	// add fd of libgsm
	Fl::add_fd(fd_lgsm, handle_lgsm);
	// UI construction
	make_window();
	// start event loop
	return Fl::run();
}
