// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Fl_App_h
#define Fl_App_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Button.H>

#include <flphone/theme.h>
#include <ipc/tbus.h>

class Fl_App : public Fl_Window {
public:
 // TODO fix default values
//  Fl_App(int X, int Y, int W=176, int H=200, const char *L = 0);
  Fl_App(const char *L = 0, bool leftmenu = false, bool rightsoft = false);
  ~Fl_App();
// widget constructor
  Fl_Scroll *AppArea;
  Fl_Menu_Button *LeftSoftMenu;
  Fl_Button *LeftSoft;
  Fl_Menu_Button *RightSoftMenu;
  Fl_Button *RightSoft;

private:
	int AppState;		// Current App state (user controlled)
	int tbus_socket;	// Socket fd for T-BUS connection
	static void handle_tbus_message(int fd, void *data);
protected:
	virtual void handle_signal(struct tbus_message *msg);
	virtual void handle_method(struct tbus_message *msg);
	virtual void handle_method_return(struct tbus_message *msg);
	virtual void handle_error(struct tbus_message *msg);
};

#endif
