// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Application_h
#define Application_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Button.H>

#include <flphone/theme.h>
#include <ipc/tbus.h>

class Fl_App : public Fl_Window {
public:
 // TODO fix default values
//  Fl_App(int X, int Y, int W=176, int H=200, const char *L = 0);
  Fl_App(const char *L = 0);
  ~Fl_App();
// widget constructor
  Fl_Scroll *AppArea;
  Fl_Menu_Button *LeftSoft;
  Fl_Button *RightSoft;
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Move_i(Fl_Menu_*, void*);
  static void cb_Move(Fl_Menu_*, void*);
  void cb_RightSoft_i(Fl_Menu_Button*, void*);
  static void cb_RightSoft(Fl_Menu_Button*, void*);
};

#endif
