// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef pin_enter_h
#define pin_enter_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Menu_Button.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *win_pin;
  Fl_Input *pin_code;
private:
  void cb_pin_code_i(Fl_Input*, void*);
  static void cb_pin_code(Fl_Input*, void*);
public:
  Fl_Menu_Button *LeftSoft;
  Fl_Menu_Button *RightSoft;
private:
  void cb_RightSoft_i(Fl_Menu_Button*, void*);
  static void cb_RightSoft(Fl_Menu_Button*, void*);
};
#endif
