// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "pin-enter.h"

void UserInterface::cb_pin_code_i(Fl_Input*, void*) {
  //pin code;
}
void UserInterface::cb_pin_code(Fl_Input* o, void* v) {
//  ((UserInterface*)(o->parent()->user_data()))->cb_pin_code_i(o,v);
}

void UserInterface::cb_RightSoft_i(Fl_Menu_Button*, void*) {
  // Close program;
}
void UserInterface::cb_RightSoft(Fl_Menu_Button* o, void* v) {
//  ((UserInterface*)(o->parent()->user_data()))->cb_RightSoft_i(o,v);
}

Fl_Double_Window* UserInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win_pin = new Fl_Double_Window(176, 200, "PIN-code");
    w = o;
    o->box(FL_NO_BOX);
    o->user_data((void*)(this));
    { Fl_Input* o = pin_code = new Fl_Input(0, 101, 176, 34);
      o->box(FL_DOWN_FRAME);
      o->color((Fl_Color)19);
      o->textsize(18);
      o->callback((Fl_Callback*)cb_pin_code);
      o->when(FL_WHEN_CHANGED);
    }
    { Fl_Menu_Button* o = LeftSoft = new Fl_Menu_Button(0, 180, 88, 20, "Options");
      o->box(FL_FLAT_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    }
    { Fl_Menu_Button* o = RightSoft = new Fl_Menu_Button(88, 180, 88, 20, "Close");
      o->box(FL_FLAT_BOX);
      o->labeltype(FL_SHADOW_LABEL);
      o->callback((Fl_Callback*)cb_RightSoft);
      o->when(FL_WHEN_ENTER_KEY_ALWAYS);
    }
    o->end();
  }
  return w;
}

int main(int argc, char **argv) {
	int fd_ipc;
	int fd_lgsm;
	UserInterface ui;

//	fd_ipc = tbus_register_service("Phone");
//	fd_lgsm = init_lgsm();

	// add fd of IPC messages
//	Fl::add_fd(fd_ipc, tbus_handle);
	// add fd of libgsm
//	Fl::add_fd(fd_lgsm, lgsm_handle);
	// UI construction
	ui.make_window();
	ui.win_pin->show(argc, argv);
	
	return Fl::run();
}
