// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef Application_h
#define Application_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Button.H>

#include <flphone/theme.h>

class AppView : public Fl_Group {
public:
 // TODO fix default values
  AppView(int X, int Y, int W=176, int H=200, const char *L = 0);
// widget constructor
  Fl_Scroll *AppArea;
  Fl_Menu_Button *LeftSoft;
  Fl_Button *RightSoft;
private:
  void cb_Open_i(Fl_Menu_*, void*);
  static void cb_Open(Fl_Menu_*, void*);
  void cb_Move_i(Fl_Menu_*, void*);
  static void cb_Move(Fl_Menu_*, void*);
  void cb_RightSoft_i(Fl_Menu_Button*, void*);
  static void cb_RightSoft(Fl_Menu_Button*, void*);
};


// main
#include <FL/Fl_Double_Window.H>


class Fl_Grid : public Fl_Scroll {
private:
	int	_cols;	// current number of columns
	int	_hspace;//horizontal spacing between items in the grid
	int	_vspace;
public:
	// constructor
	Fl_Grid(int x, int y, int w=176, int h=180, const char *label = 0);
	// add the widget to the grid
	void add_item(Fl_Widget *w);
	// remove the widget from the grid
	void remove_item(Fl_Widget *w);

	int columns()	// get the current number of columns
		{	return _cols;
		}
	void columns(int cols)// set the current number of columns
		{	_cols = cols;
		}
};


extern Fl_Double_Window *AppWindow;
extern AppView *appview;
#endif
