// generated by Fast Light User Interface Designer (fluid) version 1.0108

//#include <libintl.h>
#include <flgui/Fl_App.h>
#include <flgui/Fl_Grid.h>

#include <stdio.h>

void cb_Open(Fl_Menu_ * o, void *v)
{
	// Open cb
	printf("cb_Open\n");
	o->label("Close");
}

void cb_Move(Fl_Menu_ * o, void *v)
{
	// Move cb
	printf("cb_Move\n");
	o->label("Moved");
}

// declaration of the menu
static Fl_Menu_Item menu_LeftSoft[] = {
	{"Open", 0, (Fl_Callback *) cb_Open, 0, 0, FL_NORMAL_LABEL, 0,
	 14, 0},
	{"Move", 0, (Fl_Callback *) cb_Move, 0, 0, FL_NORMAL_LABEL, 0,
	 14, 0},
	{0, 0, 0, 0, 0, 0, 0, 0, 0}
};

// callback for the Right softkey
void cb_RightSoft(Fl_Menu_Button * o, void *v)
{
	// print the index of the
	printf("cb_RightSoft\n");
	o->label("test2");
}

//---------------------------------------------------------------------

// main
Fl_App *appview = (Fl_App *) 0;
Fl_Grid *grid = (Fl_Grid *) 0;

Fl_Button *btn1 = (Fl_Button *) 0;
Fl_Button *btn2 = (Fl_Button *) 0;

static void cb_btn1(Fl_Button * o, void *)
{
	o->label("turn");
}

int main(int argc, char **argv)
{
	// Create application window
	{
		// Create application view
		{
			appview = new Fl_App("Test app");
			// add left softkey menu
			appview->LeftSoft->menu(menu_LeftSoft);

			// add right softkey menu (another way to do this)
			appview->RightSoft->
			    callback((Fl_Callback *) cb_RightSoft);

			{
				btn1 =
				    new Fl_Button(25, 25, 48, 35,
						  "Test");
				btn1->callback((Fl_Callback *) cb_btn1);
			}	// Fl_Button* btn1
			{
				btn2 =
				    new Fl_Button(25, 250, 48, 35,
						  "Test");
			}	// Fl_Button* btn2

//			appview->AppArea->add(btn1);
//			appview->AppArea->add(btn2);
			grid = new Fl_Grid(0, 0);
			grid -> add_item(btn1);
			grid -> add_item(btn2);
			appview->AppArea->add(grid);

		}		// AppView* appview
	}			// Fl_Double_Window* AppWindow
	appview->show(argc, argv);
	return Fl::run();
}
