// generated by Fast Light User Interface Designer (fluid) version 1.0108

//#include <libintl.h>
#include "flgui/Fl_App.h"

//---------------------------------------------------------------------
Fl_App::Fl_App(const char *L)
:Fl_Window(0, 0, APPVIEW_WIDTH, APPVIEW_HEIGHT, L)
{
// widget constructor
	AppArea = new Fl_Scroll(0, 0, APPVIEW_WIDTH, APPVIEW_AREA_HEIGHT);
	AppArea->end();
	// Fl_Scroll* AppArea
	LeftSoft = new Fl_Menu_Button(0, APPVIEW_AREA_HEIGHT, 
			APPVIEW_WIDTH / 2, APPVIEW_CONTROL_HEIGHT, "Options");
	// Fl_Menu_Button* LeftSoft
	RightSoft = new Fl_Button(APPVIEW_WIDTH / 2, APPVIEW_AREA_HEIGHT,
			APPVIEW_WIDTH / 2, APPVIEW_CONTROL_HEIGHT, "Close");
	// Fl_Menu_Button* RightSoft
	end();	
}

Fl_App::~Fl_App()
{
    delete AppArea;
    delete LeftSoft;
    delete RightSoft;
}
